In [ ]:
import numpy as np

method to create an array of numpy

In [ ]:
lst=[1,4,3,6,4,0,4,5]
arr=np.array(lst)

In [ ]:
arr.shape

(8,)

In [ ]:
arr[2]

3

In [ ]:
arr[6]

4

In [ ]:
arr[2]=77

In [ ]:
arr

array([ 1,  4, 77,  6,  4,  0,  4,  5])

In [ ]:
arr[3:9]

array([6, 4, 0, 4, 5])

In [ ]:
arr[:-1]

array([ 1,  4, 77,  6,  4,  0,  4])

In [ ]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr1[:,[0,4]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["R1","R2", "R3","R4","R5"], columns=["col1", "col2","col3","col4"])

In [ ]:
df

col1  col2  col3  col4
R1     0     1     2     3
R2     4     5     6     7
R3     8     9    10    11
R4    12    13    14    15
R5    16    17    18    19

In [ ]:
df.iloc[:,[0,3]]

col1  col4
R1     0     3
R2     4     7
R3     8    11
R4    12    15
R5    16    19

another method to create an array of numpy
stride

In [ ]:
import numpy as np

In [ ]:
np.arange(1,10,1) # 1=start; 10=stop; 1=step/jump

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

rehspae this numpy array as below

In [ ]:
np.arange(1,10,1).reshape(3,3) # 3=rows; 3=columns ; 2 Dimension array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,20,2) #1-20 with the distance of 2 are 10 elements

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(1,20,2).reshape(2,5,1) #  3D array

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [ ]:
np.ones((7,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros_like(np.ones((4,4)))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])